# Your name and what you do
name: Jayant Parchuré

bio: Analytics | Product | Design

description: Jayant's Personal Website

# Profile picture
picture: assets/images/PP_TGT_small.jpg

# your url: http://USERNAME.github.io
url: https://jparchure.github.io/Eve/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
twitter: jparchure
linkedin: jayantparchure
github: jparchure
email: jayantparchure@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
medium: jayp
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: true

# do you want to display a skills section? true or false
skills: false

# add your skills here
skills-list:
    - Data Analysis
    - Data Visualization
    - Product Development
    - Programming  

# do you want to display a projects section? true or false
projects: false

# add your projects here
project-list:
    Eve:
        name: Eve
        description: Ultra Minimal Single-page Jekyll Template for Building Personal Portfolio Websites
        url: https://github.com/jibolash/Eve
    World-Cup-History:
        name: World Cup  History
        description: npm package for FIFA World cup historical data
        url: https://github.com/jibolash/world-cup-history
    Tweeter:
        name: Tweeter
        description: A Twitter inspired web application built with Angular 5
        url: https://tweetermum.herokuapp.com
    Transcend:
        name: Transcend
        description: An android app for meditation and mindfulness
        url: https://github.com/Khosbayar/Transcend

# Google Analytics
google_analytics: UA-89668075-1

# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
